# Dependencies
markdown:            kramdown
highlighter:         rouge

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: false

# Setup
title:            JuanDavid8a
tagline:          'for ($i = 1; $i <= 1000; $i++){ echo "Be Happy"; }'
description:      'Experto en Sistematización de Procesos en la Nube (Test-driven development (TDD), Behavior Driven Development (BDD), PHPunit, Metodologías Ágiles (Scrum), Bitbucket Pipelines (Atlassian), Amazon Web Service Administrator, Control de versiones (GIT), Bases de datos no relacionales (mongoDB), SOAP WebServices (C#), ERP SAP Business One (SDK - UIAPI), TCP server (Sockets)), jugador de PaintBall, Roller Derby, Gomoso de la Robótica, Electrónica y La Tecnología.'
url:              http://juandavid8a.github.io

author:
  name:           'Juan David Ochoa'
  url:            http://juandavid8a.github.io
  gravatar:       https://es.gravatar.com/juandavid8a160218
  photo:          https://s.gravatar.com/avatar/cd52071b4f9bd4270c077c653c8ca1d7?s=350
  introduction:   'Full Stack Developer experto en Sistematización de Procesos en la Nube, Jugador de PaintBall, Roller Derby, Gomoso de la Robótica, Electrónica y La Tecnología.'
  contact:        'juandavid8a@gmail.com<br>(+57) 3052370311<br>Medellín - Colombia'

paginate:         5
paginate_path:    '/blog/page:num'

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/juandavid8a
